app/routes/routes_agendar.py
from flask import render_template, request
from flask_login import login_required, current_user
from flask import Blueprint, flash, redirect, url_for
from datetime import datetime, time, date

from ..models.ModeloUsuario import ModeloUsuario
from ..models.ModeloAgenda import ModeloAgendamiento
from ..models.ModeloServicios import ModeloServicio
from ..models.entities.Correo import Correo

agendar_blueprint = Blueprint('agendar', __name__)

# Ruta de agendar servicio
@agendar_blueprint.route('/agendar', methods=['POST'])
@login_required
def agendar_route():
    operador_id = request.form.get('idOperador')
    service_id = request.form.get('id')
    service = ModeloServicio.get_by_id(service_id)
    operator = ModeloUsuario.get_by_id(operador_id)
    return render_template('services/agendar-servicio.html', usuario = current_user, servicio = service, operador = operator)

@agendar_blueprint.route('/crear_agendamiento', methods=['POST'])
@login_required
def crear_agendamiento():
    disponibilidad = request.form.get('disponibilidad')
    idServicio = request.form.get('idServicio')
    idDuenio = request.form.get('idDuenio')
    
    fecha = request.form.get('fecha')
    hora = request.form.get('hora')
    direccion = request.form.get('direccion')    

    # comprobar si no eres el mismo dueño del servicio
    if (str(current_user.id) == str(idDuenio)):
        flash("No puede agendar su propio servicio. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    
    duenio = ModeloUsuario.get_by_id(idDuenio)
    service = ModeloServicio.get_by_id(idServicio)

    correo = Correo() 

    hora_entregada = datetime.strptime(hora, '%H:%M').time()
    fecha_seleccionada = datetime.strptime(fecha, '%Y-%m-%d').date()

    # comprobar que la fecha sea mayor a la actual
    if (fecha_seleccionada < date.today()):
        flash("La fecha selecionada es anterior a la actual. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    
    aux1 = ModeloAgendamiento.agendamiento_existente(current_user.id, fecha, hora)
    if (aux1):
        flash("Usted ya tiene agendado este servicio para esta fecha. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    else:
        if ((disponibilidad == 'Todo el día') or (disponibilidad == 'Virtual')):
            aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
            if aux2:
                flash("Su agendamiento ha sido creado.")
                correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
            else:
                flash("Error al crear su agendamiento.")

        elif ((disponibilidad == 'Por la mañana')):
            if (hora_entregada > time(6,0) and hora_entregada < time(12,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        elif ((disponibilidad == 'Por la tarde')):
            if (hora_entregada > time(13,0) and hora_entregada < time(17,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        elif ((disponibilidad == 'Por la noche')):
            if (hora_entregada > time(18,0) and hora_entregada < time(23,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        return redirect(url_for('descripcion_servicios', id = idServicio))

#Eliminar un servicio Favorito
@agendar_blueprint.route('/eliminar_agendamiento', methods=['POST'])
@login_required
def eliminar_agendamiento():
    agendamiento_id = request.form.get('agendamiento_id')
    eliminado = ModeloAgendamiento.eliminar_agendamiento(idAgendamiento=agendamiento_id)
    if eliminado:
        flash("Agendamiento eliminado exitosamente.")
    else:
        flash("Error al eliminar el agendamiento.")
    return redirect(url_for('perfil'))

# Ruta protegida de agendar
@agendar_blueprint.route('/protected_agendar')
@login_required
def protected_agendar():
    return "<h1>Esta es una vista protegida para agendar un servicio.</h1>"

app/routes/routes_servicios.py
from flask import render_template, Blueprint, flash, request, get_flashed_messages, redirect, url_for
from flask_login import login_required, current_user
from ..models.entities.Servicio import Servicio
from ..models.entities.Categoria import Categoria
from ..models.entities.Busqueda import Busqueda
from ..models.ModeloServicios import ModeloServicio
from .. import db
from .. import app
from random import sample
# from uuid import uuid4  # Importar la función uuid4 para generar un nombre aleatorio
import os
#Para subir archivo tipo foto al servidor
import os
from werkzeug.utils import secure_filename

servicios_blueprint = Blueprint('servicios', __name__)

# Ruta de servicios
@servicios_blueprint.route('/servicios')
def servicios_route():
    servicios = ModeloServicio.get_all_services()  # Obtener todos los servicios desde la base de datos
    return render_template('services/servicios.html', servicios = servicios, usuario = current_user)
   

@servicios_blueprint.route('/servicios/busqueda', methods=['GET'])
def buscar_servicios():
    # Obtener el término de búsqueda ingresado por el usuario
    termino_busqueda = request.args.get('busqueda', '')
    # print(termino_busqueda)

    busqueda = Busqueda(current_user.id, termino_busqueda)
    db.session.add(busqueda)
    db.session.commit()

    # Realizar la búsqueda en la base de datos y obtener los servicios correspondientes
    servicios = ModeloServicio.buscar_servicios(termino_busqueda)

    # Renderizar el template con los resultados de la búsqueda
    return render_template('services/servicios.html', servicios=servicios, usuario = current_user, busqueda = termino_busqueda)

@servicios_blueprint.route('/servicios/busqueda_categoria', methods=['GET'])
def buscar_servicios_categoria():
    # Obtener el término de búsqueda ingresado por el usuario
    termino_busqueda = request.args.get('busqueda_categoria', '')
    try:
        # Realizar la búsqueda en la base de datos y obtener los servicios correspondientes
        servicios_cat =  Servicio.query.filter(Servicio.categoria.ilike(f'%{termino_busqueda}%')).all()
    except:
        print("aaaaah")

    # Renderizar el template con los resultados de la búsqueda
    return render_template('services/servicios.html', servicios=servicios_cat, usuario = current_user, busqueda = termino_busqueda)


@servicios_blueprint.route('/agregar_servicio', methods=['POST', 'GET'])
def agregar_servicio():

    if request.method == 'POST':  

        try:
            # Si se envía una foto a guardar
            if 'imagen' in request.files:
                file     = request.files['imagen'] #recibiendo el archivo
                imagen = recibeFoto(file) #Llamado la funcion que procesa la imagen
            else:
                imagen = ''

            # Get form data
            usuario_id = current_user.id  # Replace with actual user ID
            titulo = request.form['titulo']
            descripcion = request.form['descripcion']
            ciudad = request.form['ciudad']
            categoria = request.form['categoria']
            disponibilidad = request.form['disponibilidad']
            requisitos = request.form['requisitos']

            # Create new service
            servicio = Servicio(usuario_id, titulo, descripcion, ciudad, categoria, disponibilidad, requisitos, imagen)
            db.session.add(servicio)
            db.session.commit()

            # Si el servicio se agregó correctamente
            flash('Se ha agregado un nuevo servicio con éxito! Puede verlo en el perfil', 'success')

            cat = Categoria.query.all()  
            return render_template('services/agregar-servicio.html', categorias=cat, usuario = current_user)    
            
        except:
            # Si hubo un error al agregar el servicio
            flash('Hubo un error al agregar el servicio', 'error')
            cat = Categoria.query.all()   
            return render_template('services/agregar-servicio.html', categorias=cat, usuario = current_user)
    else:
        cat = Categoria.query.all()  
        return render_template('services/agregar-servicio.html', categorias=cat, usuario = current_user)



# Ruta protegida de servicios
@servicios_blueprint.route('/protected_servicios')
@login_required
def protected_servicios():
    return "<h1>Esta es una vista protegida para servicios.</h1>"


# Para guardar la foto con un nombre aleatorio para que no haya nombres iguales
def recibeFoto(file):
    print(file)
    basepath = os.path.dirname (__file__) #La ruta donde se encuentra el archivo actual
    print(basepath)
    filename = secure_filename(file.filename) #Nombre original del archivo

    #capturando extensión del archivo ejemplo: (.png, .jpg, .pdf ...etc)
    extension           = os.path.splitext(filename)[1]
    nuevoNombreFile     = stringAleatorio() + extension
    #print(nuevoNombreFile)
        
    upload_path = os.path.join(basepath, '..', 'static', 'img', 'uploads', nuevoNombreFile)
    file.save(upload_path)


    return nuevoNombreFile

def stringAleatorio():
    string_aleatorio = "0123456789abcdefghijklmnopqrstuvwxyz_"
    longitud         = 20
    secuencia        = string_aleatorio.upper()
    resultado_aleatorio  = sample(secuencia, longitud)
    string_aleatorio     = "".join(resultado_aleatorio)
    return string_aleatorio

#Implementacion extra
#Eliminar un servicio
@servicios_blueprint.route('/eliminar_servicio', methods=['POST'])
@login_required
def eliminar_servicio():
    try:
        servicio_id = request.form.get('servicio_id')
        eliminado = ModeloServicio.eliminar_servicio(current_user.id, servicio_id)
        if eliminado:
            flash('Servicio eliminado exitosamente', 'success')
        else:
            flash('El servicio no ha sido eliminado', 'error')
        return redirect(url_for('perfil'))
    except:
        # Si hubo un error al agregar el servicio
        flash('El servicio esta vinculado a agendamientos', 'error')
        return redirect(url_for('perfil'))

app/templates/usuario/perfil-usuario.html
{% extends '/base.html' %}
{% block titulo %}Perfil{% endblock %}
{% block autor_pagina %}Robinson Arpi{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/estilos_generales.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/estilo_perfil.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/styles_buscador.css')}}">
<link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/estilo_terminos.css')}}">
{% endblock %}

{% block cuerpo %}
    <div class = contenedor>
        <main>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <h2>Información personal</h2>
            <section class="perfil col-12 mb-3 justify-content-around">
              <div class="card col-md-2 mb-3">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ usuario.username }}</h4>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-8">
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Nombre</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        {{ usuario.nombre }} {{ usuario.apellido }}
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        {{ usuario.email }}
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Fecha de nacimiento</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        {{ usuario.fecha_nacimiento }}
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-4">
                        <button class="btn btn-sm modificar-btn boton" data-id="{{usuario.id}}" data-toggle="modal" data-target="#modalEditar">Modificar</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>  

              <div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="modalEditarLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalEditarLabel">Editar información</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <!-- Campos de edición del cliente -->
                            <form action="/actualizar_usuario/{{usuario.id}}" id="formularioEditar" method= "POST">
                              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                              <input class = "id" type="hidden" name="id" value="{{ usuario.id }}">
                              <div class = "nombre_completo">
                                  <div class = "entrada">
                                      <input class = "nombre" name = "nombre" type = "text" value="{{usuario.nombre}}" required>
                                      <label>Nombre</label>
                                  </div>
                                  <div class = "entrada">
                                      <input class = "apellido" name = "apellido" type = "text" value="{{usuario.apellido}}" required>
                                      <label>Apellido</label>
                                  </div>
                              </div>  
                                
                              <div class = "entrada">
                                  <input class = "correo" name = "email" type ="email" value="{{usuario.email}}" required >
                                  <label>Correo</label>
                              </div>
                              <div class = "passwords">
                                  <div class = "entrada">
                                      <input class = "password1" name = "password1" type = "password" required>
                                      <label>Contraseña</label>
                                  </div>
                                  <div class = "entrada">
                                      <input class = "password2" name = "password2" type = "password" required> 
                                      <label>Confirmar contraseña</label>
                                  </div>
                              </div>
                              <div class = "passwords">
                                  <div class = "entrada">
                                      <input class = "nombre" name = "username" type = "text" value="{{usuario.username}}" required>
                                      <label>Nickname</label>
                                  </div>
                                  <div class = "entrada">
                                      <input class = "f_nacimiento" type = "date" name = "fecha" id="fecha" required>
                                      <label>F. nacimiento</label>
                                  </div>
                              </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn boton" id="btn-guardar-cambios">Actualizar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
              
                
            </section>
            <section class="servicios">
                <h2>Mis Servicios</h2>
                {% if servicios %}
                  <div class="row mt-4">
                    {% for servicio in servicios %}
                      <div class="col-md-3 col-sm-6 mb-4" id="favorito1">
                          <div class="card_fav service-box">
                              <div class="card-header">
                                  <form action="{{ url_for('servicios.eliminar_servicio') }}" method="POST">
                                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                      <input type="hidden" name="servicio_id" value="{{ servicio.id }}">
                                      <button type="submit" class="btn btn-danger btn-sm float-right" id="eliminar_favorito1">
                                        <!-- icono de basurero -->
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                          </svg>
                                      </button>
                                  </form>
                              </div>
                              <img src="static/img/uploads/{{ servicio.imagen }}" class="card-img-top" alt="Servicio 1">
                              <div class="card-body">
                                  <h5 class="card-title">{{servicio.titulo}}</h5>
                                  <p class="card-text">{{servicio.descripcion}}</p>
                                  <a href="/descripcion_servicios?id={{ servicio.id }}" class="btn iniciarA">Más información</a>
                              </div>
                          </div>
                      </div>
                      {% endfor %}
                  </div>
                {% else %}
                <div class="alert alert-primary alert-dismissible" role="alert" style="background-color:#ffcff1;">
                  <strong>Aún no ha creado ningún servicio.</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
            </section>
            
            <section class="servicios">
              <h2>Servicios Agendados</h2>
              {% if agendamientos %}
              <div class="row mt-4">
                {% for serAgen in agendamientos %}
                  <div class="col-md-3 col-sm-6">
                    <a href="/descripcion_servicios?id={{ serAgen['servicio'].id }}" style="text-decoration: none; color: black;">
                      <div class="card_fav service-box">
                          <div class="card-header">
                            <h5 class="card-title" style="font-weight: bold;">📚{{serAgen['servicio'].titulo}}</h5>
                          </div>
                          <img src="static/img/uploads/{{ serAgen['servicio'].imagen }}" class="card-img-top" alt="Servicio 1">
                          <div class="card-body">
                              <p class="card-text">📆 <strong>Fecha :</strong> {{serAgen['agendamiento'].fecha}} <br> ⏰ <Strong>Hora:</Strong> {{serAgen['agendamiento'].hora}}</p>                              <form action="{{ url_for('agendar.eliminar_agendamiento') }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="agendamiento_id" value="{{ serAgen['agendamiento'].id }}">
                                <button type="submit" class="btn btn-danger btn-sm float-right" id="eliminar_favorito1">
                                  <strong>🚮 Desagendar</strong>
                                </button>
                            </form>
                          </div>
                      </div>
                    </a>
                  </div>
                {% endfor %}
              </div>
              {% else %}
                <div class="alert alert-primary alert-dismissible" role="alert" style="background-color:#ffcff1;">
                  <strong>Aún no ha realizado agendamientos de servicios.</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endif %}
            </section>

        </main>
    </div>    
    {% endblock %}    

    {% block customJS %}
      <script src="{{url_for('static', filename = 'js/funciones.js')}}"></script>
      <script src="{{url_for('static', filename = 'js/perfil_usuario.js')}}"></script>
    {% endblock %}