app/routes/routes_agendar.py
from flask import render_template, request
from flask_login import login_required, current_user
from flask import Blueprint, flash, redirect, url_for
from datetime import datetime, time, date

from ..models.ModeloUsuario import ModeloUsuario
from ..models.ModeloAgenda import ModeloAgendamiento
from ..models.ModeloServicios import ModeloServicio
from ..models.entities.Correo import Correo

agendar_blueprint = Blueprint('agendar', __name__)

# Ruta de agendar servicio
@agendar_blueprint.route('/agendar', methods=['POST'])
@login_required
def agendar_route():
    operador_id = request.form.get('idOperador')
    service_id = request.form.get('id')
    service = ModeloServicio.get_by_id(service_id)
    operator = ModeloUsuario.get_by_id(operador_id)
    return render_template('services/agendar-servicio.html', usuario = current_user, servicio = service, operador = operator)

@agendar_blueprint.route('/crear_agendamiento', methods=['POST'])
@login_required
def crear_agendamiento():
    disponibilidad = request.form.get('disponibilidad')
    idServicio = request.form.get('idServicio')
    idDuenio = request.form.get('idDuenio')
    
    fecha = request.form.get('fecha')
    hora = request.form.get('hora')
    direccion = request.form.get('direccion')    

    # comprobar si no eres el mismo dueño del servicio
    if (str(current_user.id) == str(idDuenio)):
        flash("No puede agendar su propio servicio. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    
    duenio = ModeloUsuario.get_by_id(idDuenio)
    service = ModeloServicio.get_by_id(idServicio)

    correo = Correo() 

    hora_entregada = datetime.strptime(hora, '%H:%M').time()
    fecha_seleccionada = datetime.strptime(fecha, '%Y-%m-%d').date()

    # comprobar que la fecha sea mayor a la actual
    if (fecha_seleccionada < date.today()):
        flash("La fecha selecionada es anterior a la actual. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    
    aux1 = ModeloAgendamiento.agendamiento_existente(current_user.id, fecha, hora)
    if (aux1):
        flash("Usted ya tiene agendado este servicio para esta fecha. Agendamiento no creado.")
        return redirect(url_for('descripcion_servicios', id = idServicio))
    else:
        if ((disponibilidad == 'Todo el día') or (disponibilidad == 'Virtual')):
            aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
            if aux2:
                flash("Su agendamiento ha sido creado.")
                correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
            else:
                flash("Error al crear su agendamiento.")

        elif ((disponibilidad == 'Por la mañana')):
            if (hora_entregada > time(6,0) and hora_entregada < time(12,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        elif ((disponibilidad == 'Por la tarde')):
            if (hora_entregada > time(13,0) and hora_entregada < time(17,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        elif ((disponibilidad == 'Por la noche')):
            if (hora_entregada > time(18,0) and hora_entregada < time(23,0)):
                aux2 = ModeloAgendamiento.crear_agendamiento(id_usuario = current_user.id, id_duenio= idDuenio, id_servicio = idServicio, fecha = fecha, hora=hora, direccion=direccion)
                if aux2:
                    flash("Su agendamiento ha sido creado.")
                    correo.enviar_correo(current_user.email,"Agendamiento de un servicio en el sitio Sabiduría en Línea", correo.getMessageScheduling(current_user.nombre +" "+current_user.apellido, service.titulo, duenio.nombre + " "+duenio.apellido, duenio.email))
                else:
                    flash("Error al crear su agendamiento.")
            else: 
                flash("El servicio no está disponible en este horario.")

        return redirect(url_for('descripcion_servicios', id = idServicio))

#Eliminar un servicio Favorito
@agendar_blueprint.route('/eliminar_agendamiento', methods=['POST'])
@login_required
def eliminar_agendamiento():
    agendamiento_id = request.form.get('agendamiento_id')
    eliminado = ModeloAgendamiento.eliminar_agendamiento(idAgendamiento=agendamiento_id)
    if eliminado:
        flash("Agendamiento eliminado exitosamente.")
    else:
        flash("Error al eliminar el agendamiento.")
    return redirect(url_for('perfil'))

# Ruta protegida de agendar
@agendar_blueprint.route('/protected_agendar')
@login_required
def protected_agendar():
    return "<h1>Esta es una vista protegida para agendar un servicio.</h1>"

app/templates/services/agendar-servicio.html
{% extends '/base.html' %}
{% block titulo %}Agendar un servicio{% endblock %}
{% block autor_pagina %}Kevin Juela{% endblock %}

{% block customCSS %}
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/estilo_inicio_registro.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
{% endblock %}

{% block cuerpo %}
<div class = "contenedor tamanio">
    <section class="lateral_izquierdo imagen_registro">
        <img src="../../static/Images/agendar.svg" alt="">
    </section>
    <main>
        <div class="contenedor_login">
            <p class="titulo">Agendar Servicio</p>
            <div class="separador"></div>
            <p class="mensaje_bienvenida">Por favor, ingrese los campos requeridos </p>
            <div class="section2">
                <p id="nom-servicio"> <span style="font-weight: bold;">Título:</span> {{servicio.titulo}} <br>
                <span style="font-weight: bold;">Operador:</span> {{operador.nombre}} {{operador.apellido}}  <br><span style="font-weight: bold;">Disponibilidad: </span>{{servicio.disponibilidad}}</p>
                
            </div>
            <form class="form_registro" action="{{ url_for('agendar.crear_agendamiento') }}" method = "POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="idServicio" value="{{ servicio.id }}">
                <input type="hidden" name="idDuenio" value="{{ operador.id }}">
                <input type="hidden" name="disponibilidad" value="{{servicio.disponibilidad}}">
                <div class = "entrada">
                    <input type = "date" class="fecha" name = "fecha" id="fecha" required title="Elija una fecha por favor.">
                    <label>Fecha</label>
                </div>
                <div class = "entrada">
                    <input type = "time" class="hora" name = "hora" id="hora" required title="Elija una hora de acuerdo a la disponibilidad del servicio.">
                    <label>Hora</label>
                </div>
                <div class = "entrada">
                    <input type = "text" name="direccion" class="direccion" required title="Ingrese por favor la direccion si es necesario para el servicio.">
                    <label>Dirección</label>
                </div>
                <div class = "botones-2">
                    <button class="boton boton-cancelar" onclick="borrarCampos()">Cancelar</button>
                    <button type="submit" class="boton boton-agendar" onclick="limpiarCampos()">Agregar</button>
                </div>                    
            </form>
        </div>
    </main>
</div>
{% endblock %}

{% block customJS %}
    <script src="{{url_for('static', filename = 'js/script-agendar.js')}}"></script>
{% endblock %}

app/templates/services/agregar-servicio.html
{% extends '/base.html' %}
{% block titulo %}Agregar un servicio{% endblock %}
{% block autor_pagina %}Hernán Coronel{% endblock %}

{% block customCSS %}
    <!-- Bootstrap-->
    <link rel = "stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel = "stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

    <!-- Estilos generales -->
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/estilos_generales.css')}}">    
    <!-- Mi css -->
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/estilo_agregar.css')}}">
    
{% endblock %}

{% block cuerpo %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<!-- {% with messages = mensaje_flash %}
    {% if messages %}
      <script>
        $(document).ready(function() {
          $('#mensajeModal .modal-body').text('{{ messages[0] }}');
          $('#mensajeModal').modal('show');
        });
      </script>
    {% endif %}
  {% endwith %} -->

<form method="post" id="form_agregar" enctype="multipart/form-data">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <div class="container">
    <h1 class="text-center pt-4 pb-4">Agregar servicio</h1>
    <div class="row">
      <div class="col-lg-4 col-12">
        <label for="imagen">Imagen del servicio</label>
        <div id="preview-container" class="preview-container">
          <div class="upload-area" id="upload-area">
            <span class="upload-text">Cargar imagen</span>
          </div>
          <img id="imagen-preview" src="" alt="">
          <button id="eliminar-imagen" class="eliminar-imagen" type="button">X</button>
        </div>
        <div class="subir-imagen">
          <input type="file" id="imagen" name="imagen" accept="image/*">
        </div>
      </div>     
      <div class="col-lg-4 col-12">
        <div class="form-group">
          <label for="titulo">Título</label>
          <input type="text" class="form-control" id="titulo" name="titulo">
        </div>

        <div class="form-group">
          <label for="descripcion">Descripción</label>
          <textarea class="form-control" id="descripcion" name="descripcion" rows="5"></textarea>
        </div>
        <div class="form-group">
          <label for="ciudad">Ciudad</label>
          <input type="text" class="form-control" id="ciudad" name="ciudad">
        </div>
      </div>
      <div class="col-lg-4 col-12">
        <div class="form-group">
          <label for="categoria">Categoría</label>
          <select class="form-control" id="categoria" name="categoria">
            <option selected disabled value="Seleccione ...">Seleccione ...</option>
            {% for categoria in categorias %}
              <option value={{categoria.nombre}}>{{categoria.nombre}}</option>
            {% endfor %}
          </select>          
        </div>
        <div class="form-group">
          <label for="disponibilidad">Disponibilidad</label>
          <select class="form-control" id="disponibilidad" name="disponibilidad">
            <option selected disabled value="Seleccione ...">Seleccione ...</option>
            <option value="Todo el día">Todo el día</option>
            <option value="Por la mañana">Por la mañana</option>
            <option value="Por la tarde">Por la tarde</option>
            <option value="Por la noche">Por la noche</option>
            <option value="Virtual">Virtual</option>
          </select>
        </div>
        <div class="form-group">
          <label for="requisitos">Requisitos</label>
          <div class="input-group mt-2">
            <input type="text" class="form-control" id="nuevo-requisito" placeholder="Escriba un requisito">
            <button class="btn btn-secondary boton-agregar" id="agregar-requisito" type="button">Agregar</button>
          </div>
          <ul class="list-group" id="requisitos-lista">
          </ul>
          <input type="hidden" id="requisitos" name="requisitos">
        </div>
      </div>
    </div>
    <div class="text-center mt-4 pb-4">
      <button class="boton" id="limpiar-campos"  type="button" onclick="limpiarCampos()">Limpiar campos</button>
      <button class="boton" id="agregar-servicio" >Agregar servicio</button>
    </div>
  </div>
</form>  

<!-- Modal de MostrarMensaje -->
<div class="modal fade" id="mensajeModal" tabindex="-1" role="dialog" aria-labelledby="mensajeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="mensajeModalLabel"></h5>
          <button id="XCerrarModal" type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button id="btnCerrarModal" type="button" class="btn btn-secondary" data-dismiss="modal">Aceptar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal para realizar una pregunta de si/no -->
<div class="modal fade" id="preguntaModal" tabindex="-1" role="dialog" aria-labelledby="preguntaModalLabel" aria-hidden="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="preguntaModalLabel">¡Atención!</h5>
        <button id="btnX" type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Hay un requisito que no ha sido agregado a la lista</p>
        <p>¿Desea incluirlo ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" id="XCerrar" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary">Sí</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block customJS %}
    <!-- Librería jQuery para agregar interacción-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Mi js -->
    <script src="{{url_for('static', filename = 'js/agregar_servicio.js')}}"></script>
{% endblock %}

app/templates/services/cronograma.html
{% extends '/base.html' %}
{% block titulo %}Cronograma{% endblock %}
{% block autor_pagina %}Mauro Mizhquiri{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/estilos.cronograma.css')}}">
<script>
  var listaString = '{{ lista|tojson }}';
  var lista = JSON.parse(listaString);
</script>
{% endblock %}


{% block cuerpo %}
<div class="contenedor">
  <div class="left">
    <div class="calendar">
      <div class="month">
        <i class="fas fa-angle-left prev"></i>
        <div class="date">december 2015</div>
        <i class="fas fa-angle-right next"></i>
      </div>
      <div class="weekdays">
        <div>Dom</div>
        <div>Lun</div>
        <div>Ma</div>
        <div>Mie</div>
        <div>Jue</div>
        <div>Vie</div>
        <div>Sab</div>
      </div>
      <div class="days"></div>


      <div class="goto-today">
        <div class="goto">
          <input type="text" placeholder="mm/yyyy" class="date-input" />
          <button class="goto-btn">Ir</button>
        </div>
        <button class="today-btn">Hoy</button>
      </div>
    </div>
  </div>

  <div class="right">
    <div class="today-date">
      <div class="event-day">Mie</div>
      <div class="event-date">19 Julio 2023</div>
    </div>
    
    <div class="events"></div>

    <div class="botones">
      <button class="salir" onclick="salir(event)">Salir</button>
    </div>
  </div>
</div>

{% endblock %}

{% block customJS %}
<script src="{{url_for('static', filename = 'js/cronograma.js')}}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

app/templates/services/descripcion_servicios.html
{% extends '/base.html' %}
{% block titulo %}Descripción servicios{% endblock %}
{% block autor_pagina %}Mauro Mizhquiri{% endblock %}


{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/estilo_descripcion_servicios.css')}}">
{% endblock %}


{% block cuerpo %}
<div class="container">

  <div class="contenedor_derecho">
    <div class="imagen_descripcion">
      <img src="{{ url_for('static', filename='img/uploads/' + servicio.imagen) }}" alt="" class="card-img-top">
    </div>
    <div class="favoritos">
      <form action="{{ url_for('agregar_a_favoritos') }}" method="POST">
        <!-- Incluye el token CSRF en tu formulario -->
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        {% if favorito %}
        <script>
          window.onload = function () {
            cambiarColor();
          };
        </script>
        {% endif %}
        <input type="hidden" name="id" value="{{ servicio.id }}">
        <button type="submit" class="fav" onclick="cambiarColor()">
          <svg id="corazon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
          </svg>
          <span id="texto">Agregar a favoritos</span>
        </button>
        <input type="hidden" name="texto_valor" id="texto_valor">


      </form>
    </div>



  </div>

  <main>

    <div class="contenedor_servicio">

      <div class="titulo_curso">
        <span>{{ servicio.titulo }}</span>
      </div>

      <section class="imagen_descripcion2">
        <img src="../Images/curso_computación.jpg" alt="">
      </section>

      <div class="separador"></div>



      <p class="descripcion-servicio">{{ servicio.descripcion }}</p>


      <div class="informacion">
        <p class="categoria-servicio"><strong>Categoria:</strong> {{ servicio.categoria }}</p>
        <p class="ubicacion-servicio"><b>Ubicación:</b> {{ servicio.ciudad }}</p>
        <p class="disponibilidad-servicio"><b>Disponibilidad:</b> {{ servicio.disponibilidad }}</p>
      </div>

      <div class="requisitos-servicio">
        <b>Requisitos</b>

        <div class="requisitos">
          {% set requisitos_lista = servicio.requisitos.split('X') %}
          {% for requisito in requisitos_lista %}
          {% if loop.index > 1 %}
          <span>{{ requisito|trim(';') }}</span>
          {% else %}
          <span>{{ requisito }}</span>
          {% endif %}
          {% endfor %}
        </div>
      </div>

      {% with messages = get_flashed_messages() %}
          {% if messages %}
              {% for message in messages %}
              <div class="alert alert-primary alert-dismissible" role="alert" style="background-color:#ffcff1">
                  <strong>{{ message }}</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
          {% endif %}
      {% endwith %}
            
      <div class="botones">
        <form action="{{ url_for('agendar.agendar_route') }}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <input type="hidden" name="id" value="{{ servicio.id }}">
          <input type="hidden" name="idOperador" value="{{ servicio.usuario_id }}">
          <button type="submit" class="agendar-servicio">Agendar Servicio</button>
        </form>
        <button class="Cancelar" onclick="cancelar(event)"></i> Cancelar</button>
      </div>

    </div>
  </main>
</div>

{% endblock %}

{% block customJS %}
<script src="{{url_for('static', filename = 'js/descripcion_servicio.js')}}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% endblock %}

app/templates/services/servicios.html
{% extends '/base.html' %}
{% block titulo %}Servicios{% endblock %}
{% block autor_pagina %}Hernán Coronel{% endblock %}

{% block customCSS %}

<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Mi css -->
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/estilo_servicios.css')}}">

<!-- Font awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock %}

{% block cuerpo %}
<main>
  <!-- Servicios -->
  <div class="container">
    {% if servicios %}
      {% if busqueda %}
      <div class="search-results center-content">
        Resultados para: "{{ busqueda }}"
        <br>
        <a class="link-servicios" href="/servicios">Mostrar todos los servicios</a>
      </div>
      {% endif %}
      <div class="row card-deck">
        {% for servicio in servicios %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-6  mb-3">
          <!-- Aquí poner la ruta con el id -->
          <a href="/descripcion_servicios?id={{ servicio.id }}">
            <div class="card clickable">
              <img src="static/img/uploads/{{ servicio.imagen }}" class="card-img-top" alt="...">
              <div class="card-body">
                <label hidden>{{ servicio.id }}</label>
                <h5 class="card-title">{{ servicio.titulo }}</h5>
                <p class="card-text">{{ servicio.descripcion }}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
    {% else %}
      {% if busqueda %}
        <div class="search-results center-content">
          Resultados para: "{{ busqueda }}"
          <br>
          <a class="link-servicios" href="/servicios">Mostrar todos los servicios</a>
        </div>
      {% endif %}
      <div class="no-services text-center">
        <i class="bi bi-emoji-frown"></i>
        <p>No se encontraron servicios aún. ¡Vuelve pronto!</p>
      </div>
    {% endif %}
  </div>
</main>

{% endblock %}

{% block customJS %}
<script src="{{url_for('static', filename = 'js/servicios.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% endblock %}