app/routes/routes_favoritos.py
from flask import render_template
from flask_login import login_required, current_user
from flask import Blueprint, render_template, flash, request, redirect, url_for

from ..models.ModeloServicios import ModeloServicio
from ..models.ModeloFavoritos import ModeloFavorito

favoritos_blueprint = Blueprint('favoritos', __name__)

# Ruta de favoritos servicio
@favoritos_blueprint.route('/favoritos')
@login_required
def favoritos_route():
    lista_ids = ModeloFavorito.get_favorites_idUser(current_user.id)
    l_service = ModeloServicio.get_by_listFavoritos(lista_ids)
    if len(l_service) == 0:
        flash("Usted no tiene servicios favoritos.")
    return render_template('favorites/favoritos.html', usuario = current_user, lista_servicios = l_service)
    
#Eliminar un servicio Favorito
@favoritos_blueprint.route('/eliminar_favorito', methods=['POST'])
@login_required
def eliminar_favorito():
    servicio_id = request.form.get('servicio_id')
    eliminado = ModeloFavorito.eliminar_favorito(current_user.id, servicio_id)
    if eliminado:
        flash("Favorito eliminado exitosamente.")
    else:
        flash("Error al eliminar el favorito.")
    return redirect(url_for('favoritos.favoritos_route'))

# Ruta protegida de historial
@favoritos_blueprint.route('/protected_favoritos')
@login_required
def protected_favoritos():
    return "<h1>Esta es una vista protegida para favoritos de un usuario.</h1>"

app/templates/favorites/favoritos.html
{% extends '/base.html' %}
{% block titulo %}Servicios Favoritos{% endblock %}
{% block autor_pagina %}Kevin Juela{% endblock %}

{% block customCSS %}
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/styles_buscador.css')}}">
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'css/estilo_terminos.css')}}">
{% endblock %}

{% block cuerpo %}
<header class="border">
    <h1>Favoritos</h1>
</header>
<div class="container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary alert-dismissible" role="alert" style="background-color:#ffcff1;">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row mt-4">
        {% for serFav in lista_servicios %}
        <div class="col-md-3 col-sm-6 mb-4" id="favorito1">
            <div class="card_fav service-box">
                <div class="card-header">
                    <form action="{{ url_for('favoritos.eliminar_favorito') }}" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="servicio_id" value="{{ serFav.id }}">
                        <button type="submit" class="btn btn-danger btn-sm float-right" id="eliminar_favorito1">
                            <!-- icono de basurero -->
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                            </svg>
                        </button>
                    </form>
                </div>
                <img src="static/img/uploads/{{ serFav.imagen }}" class="card-img-top" alt="Servicio 1">
                <div class="card-body">
                    <h5 class="card-title">{{serFav.titulo}}</h5>
                    <p class="card-text">{{serFav.descripcion}}</p>
                    <a href="/descripcion_servicios?id={{ serFav.id }}" class="btn iniciarA">Más información</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block customJS %}
    <!-- <script src="{{url_for('static', filename = 'js/favoritos.js')}}"></script> -->
{% endblock %}